#!/bin/bash

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

VERSION="0.9"
TOKEN=""
CHATS=()
DEBUG=false
DRY_RUN=false

IMAGE_FILE=""
DOCUMENT_FILE=""
VIDEO_FILE=""
PARSE_MODE=""
CODE_MODE=0
CRON_MODE=0
ACTION=""
TITLE=""
DISABLE_WEB_PAGE_PREVIEW=false
DISABLE_NOTIFICATION=false

URL="https://api.telegram.org/bot"
FILE_URL="https://api.telegram.org/file/bot"
# Default network behavior: fail a connection attempt after 10s and cap the
# whole transfer at 300s (headroom for a 50MB upload on a slow uplink), so a
# dead proxy or a hung TCP session can't block a cronjob forever.
# Overridable via CURL_OPTIONS in a config file.
CURL_OPTIONS="-s --connect-timeout 10 --max-time 300"
RETRIES=1
RETRY_DELAY=2
PARALLEL=false

HAS_JQ=false
hash jq >/dev/null 2>&1 && HAS_JQ=true


function help {
	version
	echo "Usage: $0 [options] [message]"
	echo
	echo "OPTIONS are:"
	echo "    -t <TOKEN>       Telegram bot token to use. See ENVIRONMENT for more information."
	echo "    -c <CHAT_ID>     Chat to use as recipient. Can be given more than once. See ENVIRONMENT for more information."
	echo "    -a <N>           Attempts per recipient (retries). Recipients are independent. Only transient failures"
	echo "                     (network errors, HTTP 5xx, 429 rate-limit) are retried; permanent errors fail fast."
	echo "                     429 'retry_after' is honored. Default: 1 (no retry)."
	echo "    -p               Deliver to all recipients in parallel (independently) instead of one after another."
	echo "    -f <FILE>        Sends file."
	echo "    -i <FILE>        Sends file as image. This will fail if the file isn't an actual image file."
	echo "    -V <FILE>        Sends file as video."
	echo "    -M               Enables Markdown processing at telegram."
	echo "    -H               Enables HTML processing at telegram."
	echo "    -C               Sends text as monospace code. Useful when piping command outputs into this tool."
	echo "    -r               Like -C, but if the first line starts with '+ ', it is specially formatted."
	echo "    -T <TITLE>       Sets a title for the message. Printed in bold text if -M or -H is used."
	echo "    -l               Fetch known chat_ids."
	echo "    -R               Receive a file sent via telegram."
	echo "    -D               Disable the web-page preview for links (via link_preview_options)."
	echo "                     Can also be set in config as TELEGRAM_DISABLE_WEB_PAGE_PREVIEW=true (see ENVIRONMENT)"
	echo "                     This feature is only supported for text messages, not when sending files or images (-f, -i)."
	echo "    -N               Diables notifications on clients. Users will receive a notification with no sound."
	echo "                     Can also be set in config as TELEGRAM_DISABLE_NOTIFICATION=true (see ENVIRONMENT)"
	echo "    -m               Outputs the last received message. Format is: <Message ID> <Sender ID> <Chat ID> <Text>"
	echo
	echo "DEBUGGING OPTIONS are:"
	echo "    -v               Display lots of more or less useful information."
	echo "    -j               Pretend you don't have JQ installed."
	echo "    -n               Dry-run - don't send messages, only print them on screen."
	echo
	echo "Message can be '-', in that case STDIN will be used."
	echo
	echo "ENVIRONMENT"
	echo "    TOKEN and CHAT_ID are required. You can set them in six different ways:"
	echo "      1) globally in /etc/telegram.sh.conf"
	echo "      2) user-local in ~/.telegram.sh"
	echo "      3) user-local in ~/.telegram.sh.conf"
	echo "      4) relative to this script in `dirname "$0"`/.telegram.sh.conf"
	echo "      5) via environment variables TELEGRAM_TOKEN and TELEGRAM_CHAT"
	echo "      6) via options -t and -c"
	echo "    Later methods overwrite earlier settings, so you can easily override global settings."
	echo "    Please be aware that you shuld keep your telegram token secret!"
	echo
	exit
}

function version {
	echo "telegram.sh version $VERSION"
	echo "by Fabian Schlenz"
}

function list_chats {
	log "$URL$TOKEN"
	# shellcheck disable=SC2086 # CURL_OPTIONS word splitting is documented
	response=$(curl $CURL_OPTIONS "$URL$TOKEN/getUpdates")
	log "$response"

	if [ "$HAS_JQ" = true ]; then
		echo "These are the available chats that I can find right now. The ID is the number at the front."
		echo "If there are no chats or the chat you are looking for isn't there, run this command again"
		echo "after sending a message to your bot via telegram."
		echo
		jq -r '.result | .[].message.chat | "\(.id|tostring) - \(.first_name) \(.last_name) (@\(.username))"' 2>/dev/null <<< "$response" || {
			echo "Could not parse reponse from Telegram."
			echo "Response was: $response"
			exit 1
		}
	else
		echo "You don't have jq installed. I'm afraid I can't parse the JSON from telegram without it."
		echo "So I'll have you do it. ;-)"
		echo
		echo "Please look for your chat_id in this output by yourself."
		echo 'Look for something like "chat":{"id":<CHAT_ID> and verify that first_name, last_name and'
		echo "username match your expected chat."
		echo
		echo "If there are no chats listed or the chat you are looking for isn't there, try again after"
		echo "sending a message to your bot via telegram."
		echo
		echo $response
	fi
}

function receive_message {
	if [ "$HAS_JQ" = false ]; then
		echo "You need to have jq installed in order to be able to receive messages."
		exit 1
	fi
	
	# shellcheck disable=SC2086 # CURL_OPTIONS word splitting is documented
	result=$(curl $CURL_OPTIONS "$URL$TOKEN/getUpdates?allowed_updates=message")
	log "$result"
	if [ "$(jq '.result' <<< "$result")" = "[]" ]; then
		echo "No recent messages."
		exit 1
	fi
	
	jq -r '.result[-1].message | [(.message_id|tostring), (.from.id|tostring), (.chat.id|tostring), .text] | join(" ")' <<< "$result"
	exit 0
}
		

function receive_file {
	if [ "$HAS_JQ" = false ]; then
		echo "You need to have jq installed in order to be able to download files."
		exit 1
	fi

	# shellcheck disable=SC2086 # CURL_OPTIONS word splitting is documented
	result=$(curl $CURL_OPTIONS "$URL$TOKEN/getUpdates?allowed_updates=message")
	log "$result"
	# {"ok":true,"result":[
	#   {
	#     "update_id":441727866,
	#     "message":{
	#       "message_id":8339,
	#       "from":{"id":15773,"is_bot":false,"first_name":"Fabian","last_name":"Schlenz","username":"fabianonline","language_code":"de"},
	#       "chat":{"id":15773,"first_name":"Fabian","last_name":"Schlenz","username":"fabianonline","type":"private"},
	#       "date":1526564127,
	#       "document":{"file_name":"desktop.ini","file_id":"BQAav-HkXugI","file_size":282}}}]}
	file_id=`jq -r '.result[-1].message.document.file_id' <<< "$result"`
	log "file_id: $file_id"
	if [ "$file_id" == "null" ]; then
		echo "Last message received apparently didn't contain a file. Aborting."
		exit 1
	fi
	file_name=`jq -r '.result[-1].message.document.file_name' <<< "$result"`
	# The name comes from the sender - strip any path components.
	file_name="${file_name//\//_}"
	log "file_name: $file_name"
	# shellcheck disable=SC2086 # CURL_OPTIONS word splitting is documented
	result=$(curl $CURL_OPTIONS "$URL$TOKEN/getFile?file_id=$file_id")
	log "$result"
	# {"ok":true,"result":{"file_id":"BQAav-HkXugI","file_size":282,"file_path":"documents/file_271.ini"}}
	path=`jq -r '.result.file_path' <<< "$result"`
	log "path: $path"
	if [ "$path" == "null" ]; then
		echo "Could not parse telegram's response to getFile. Aborting."
		exit 1
	fi
	file_name="`date +%s`_$file_name"
	log "file_name: $file_name"
	if [ -e "$file_name" ]; then
		echo "File $file_name already exists. This is unexpected, so I'm quitting now."
		exit 1
	fi
	curl "$FILE_URL$TOKEN/$path" --output "$file_name"
	echo "File downloaded as $file_name"
}

function log {
	[ "$DEBUG" = true ] && echo "DEBUG: $1"
}

function check_file {
	local limit_mb="${2:-50}"
	if [ ! -e "$1" ]; then
		echo "The file $1 does not exist."
		exit 1
	fi

	case "$(uname -s)" in
		Darwin*) # OSX
			size=$(stat -f%z "$1");;
		*)
			size=$(stat --printf="%s" "$1");;
	esac
	if (( size > limit_mb * 1024 * 1024 )); then
		echo "File $1 is breaking the ${limit_mb}MB size limit Telegram imposes on bots for this upload type."
		exit 1
	fi
}

function escapeMarkdown {
	res="${1//\*/∗}"
	res="${res//_/＿}"
	res="${res//\`/‵}"
	#res="${res//\//∕}"
	echo "$res"
}

while getopts ":pa:t:c:i:f:V:MHCrhlvjnRmDNT:" opt; do
	case $opt in
		t)
			TOKEN="$OPTARG"
			;;
		c)
			CHATS+=("$OPTARG")
			;;
		a)
			RETRIES="$OPTARG"
			;;
		p)
			PARALLEL=true
			;;
		i)
			IMAGE_FILE="$OPTARG"
			;;
		f)
			DOCUMENT_FILE="$OPTARG"
			;;
		V)
			VIDEO_FILE="$OPTARG"
			;;
		M)
			PARSE_MODE="Markdown"
			;;
		H)
			PARSE_MODE="HTML"
			;;
		C)
			PARSE_MODE="Markdown"
			CODE_MODE=1
			;;
		r)
			PARSE_MODE="Markdown"
			CRON_MODE=1
			;;
		l)
			ACTION="list_chats"
			;;
		v)
			DEBUG=true
			;;
		j)
			HAS_JQ=false
			;;
		n)
			DRY_RUN=true
			;;
		R)
			ACTION="receive_file"
			;;
		m)
			ACTION="receive_message"
			;;
		D)
			DISABLE_WEB_PAGE_PREVIEW=true
			;;
		N)
			DISABLE_NOTIFICATION=true
			;;
		T)
			TITLE="$OPTARG"
			;;
		h)
			help
			;;
		:)
			echo "Option -$OPTARG needs an argument." >&2
			exit 2
			;;
		\?)
			echo "Invalid option -$OPTARG" >&2
			echo "Run $0 -h for help." >&2
			exit 2
			;;
	esac
done

if [ "$CRON_MODE" -eq 1 ] && [ "$CODE_MODE" -eq 1 ]; then
	echo "You can either use -C or -r, but not both."
	exit 1
fi

# Remember what came from the command line and the environment, so the
# documented precedence survives sourcing the config files:
#   config files < environment variables < command-line options.
CLI_TOKEN="$TOKEN"
CLI_CHATS=("${CHATS[@]}")
ENV_TOKEN="$TELEGRAM_TOKEN"
ENV_CHAT="$TELEGRAM_CHAT"

log "Importing config file(s)..."

[ -r /etc/telegram.sh.conf ] && source /etc/telegram.sh.conf
[ -r ~/.telegram.sh ] && source ~/.telegram.sh
[ -r ~/.telegram.sh.conf ] && source ~/.telegram.sh.conf
[ -r "$(dirname "$0")/.telegram.sh.conf" ] && source "$(dirname "$0")/.telegram.sh.conf"

# 1) Lowest priority: config files (TOKEN=/CHATS=(...) set directly, or via
#    the TELEGRAM_TOKEN / TELEGRAM_CHAT variables).
[ -z "$TOKEN" ] && TOKEN="$TELEGRAM_TOKEN"
[ ${#CHATS[@]} -eq 0 ] && read -ra CHATS <<< "$TELEGRAM_CHAT"
# 2) Environment variables override config files.
[ -n "$ENV_TOKEN" ] && TOKEN="$ENV_TOKEN"
[ -n "$ENV_CHAT" ] && read -ra CHATS <<< "$ENV_CHAT"
# 3) Command-line options override everything.
[ -n "$CLI_TOKEN" ] && TOKEN="$CLI_TOKEN"
[ ${#CLI_CHATS[@]} -gt 0 ] && CHATS=("${CLI_CHATS[@]}")

[ -n "$TELEGRAM_DISABLE_WEB_PAGE_PREVIEW" ] && DISABLE_WEB_PAGE_PREVIEW="$TELEGRAM_DISABLE_WEB_PAGE_PREVIEW"
[ -n "$TELEGRAM_DISABLE_NOTIFICATION" ] && DISABLE_NOTIFICATION="$TELEGRAM_DISABLE_NOTIFICATION"

log "TOKEN is now $TOKEN"
log "CHATS is now ${CHATS[*]}"
log "DISABLE_WEB_PAGE_PREVIEW is now $DISABLE_WEB_PAGE_PREVIEW"
log "DISABLE_NOTIFICATION is now $DISABLE_NOTIFICATION"

if [ -z "$TOKEN" ]; then
	echo "No bot token was given."
	exit 1
fi

if [ ${#CHATS[@]} -eq 0 ] && [ -z "$ACTION" ]; then
	echo "No chat(s) given."
	exit 1
fi

if [ "$ACTION" = "list_chats" ]; then
	list_chats
	exit 0
fi

if [ "$ACTION" = "receive_file" ]; then
	receive_file
	exit 0
fi

if [ "$ACTION" = "receive_message" ]; then
	receive_message
	exit 0
fi

shift $((OPTIND - 1))
TEXT="$1"
log "Text: $TEXT"

[ "$TEXT" = "-" ] && TEXT=$(</dev/stdin)

log "Text: $TEXT"

if [ $CODE_MODE -eq 1 ]; then
	TEXT='```'$'\n'$TEXT$'\n''```'
fi

if [ $CRON_MODE -eq 1 ]; then
	ONLY_COMMANDS=1
	while read line; do
		if [ "${line:0:2}" = "+ " ]; then
			ONLY_COMMANDS=0
		fi
	done <<< "$TEXT"

	if [ "$ONLY_COMMANDS" -eq 1 ]; then
		exit 0
	fi

	TEXT='```'$'\n'$TEXT$'\n''```'

	#FIRST_LINE=1
	#BLOCK_OPEN=0
	#NEW_TEXT=""
	#while read line; do
	#	if [ "${line:0:2}" = "+ " ]; then
	#		if [ "$BLOCK_OPEN" -eq 1 ]; then
	#			NEW_TEXT="$NEW_TEXT"'```'$'\n'
	#			BLOCK_OPEN=0
	#		fi
	#		NEW_TEXT="$NEW_TEXT*`escapeMarkdown "${line:2}"`*"$'\n'
	#	else
	#		if [ "$BLOCK_OPEN" -eq 0 ]; then
	#			NEW_TEXT="$NEW_TEXT"'```'$'\n'
	#			BLOCK_OPEN=1
	#		fi
	#		NEW_TEXT="$NEW_TEXT$line"$'\n'
	#	fi
	#done <<< "$TEXT"
	#[ "$BLOCK_OPEN" -eq 1 ] && NEW_TEXT="$NEW_TEXT"'```'
	#TEXT="$NEW_TEXT"
fi

log "Text: $TEXT"

if [ -n "$TITLE" ]; then
	if [ "$PARSE_MODE" == "HTML" ]; then
		TEXT="<b>$TITLE</b>"$'\n\n'"$TEXT"
	elif [ "$PARSE_MODE" == "Markdown" ]; then
		TEXT="*$TITLE*"$'\n\n'"$TEXT"
	else
		TEXT="$TITLE"$'\n\n'"$TEXT"
	fi
fi

if [ -z "$TEXT" ] && [ -z "$DOCUMENT_FILE" ] && [ -z "$VIDEO_FILE" ] && [ -z "$IMAGE_FILE" ] ; then
	echo "Neither text nor image nor video or other file given."
	exit 1
fi

if [ -n "$DOCUMENT_FILE" ] && [ -n "$IMAGE_FILE" ]; then
	echo "You can't send a file AND an image at the same time."
	exit 1
fi
if [ -n "$DOCUMENT_FILE" ] && [ -n "$VIDEO_FILE" ]; then
	echo "You can't send a file AND an video at the same time."
	exit 1
fi
if [ -n "$IMAGE_FILE" ] && [ -n "$VIDEO_FILE" ]; then
	echo "You can't send an image AND a video at the same time."
	exit 1
fi


# Arguments the script builds itself go into an array, so file names with
# spaces and other special characters survive word splitting. CURL_OPTIONS
# stays a plain string: it is a documented user knob for simple extra
# options (proxy, timeouts) and is word-split on purpose.
CURL_ARGS=()

# curl's --form parser accepts a quoted filename after @ ("..."), which makes
# spaces, commas and semicolons in paths safe. Escape per curl's quoting rules.
function form_file_arg {
	local path="$2"
	path="${path//\\/\\\\}"
	path="${path//\"/\\\"}"
	printf '%s=@"%s"' "$1" "$path"
}

[ -n "$PARSE_MODE" ] && CURL_ARGS+=(--form-string "parse_mode=$PARSE_MODE")
if [ -n "$DOCUMENT_FILE" ]; then
	check_file "$DOCUMENT_FILE"

	CURL_ARGS+=(--form "$(form_file_arg document "$DOCUMENT_FILE")")
	CURL_ARGS+=(--form "caption=<-")
	METHOD="sendDocument"
elif [ -n "$VIDEO_FILE" ]; then
	check_file "$VIDEO_FILE"

	CURL_ARGS+=(--form "$(form_file_arg video "$VIDEO_FILE")")
	CURL_ARGS+=(--form "caption=<-")
	CURL_ARGS+=(--form-string "supports_streaming=true")
	# Provide width/height/duration when ffprobe is available, so Telegram shows
	# the correct aspect ratio and a preview without having to probe the upload.
	if hash ffprobe 2>/dev/null; then
		vdims=$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height:format=duration -of default=nw=1:nk=1 "$VIDEO_FILE" 2>/dev/null | paste -sd' ' -)
		read -r vw vh vdur _ <<< "$vdims"
		[[ "$vw"   =~ ^[0-9]+$ ]] && CURL_ARGS+=(--form-string "width=$vw")
		[[ "$vh"   =~ ^[0-9]+$ ]] && CURL_ARGS+=(--form-string "height=$vh")
		[[ "$vdur" =~ ^[0-9]+   ]] && CURL_ARGS+=(--form-string "duration=${vdur%%.*}")
	fi
	METHOD="sendVideo"
elif [ -n "$IMAGE_FILE" ]; then
	check_file "$IMAGE_FILE" 10   # sendPhoto has a lower limit than documents/videos
	CURL_ARGS+=(--form "$(form_file_arg photo "$IMAGE_FILE")")
	CURL_ARGS+=(--form "caption=<-")
	METHOD="sendPhoto"
else
	CURL_ARGS+=(--form "text=<-")
	[ "$DISABLE_WEB_PAGE_PREVIEW" = true ] && CURL_ARGS+=(--form-string 'link_preview_options={"is_disabled":true}')
	METHOD="sendMessage"
fi

[ "$DISABLE_NOTIFICATION" = true ] && CURL_ARGS+=(--form-string "disable_notification=true")

if [ "$METHOD" != "sendMessage" ] && [ ${#TEXT} -gt 1024 ]; then
	echo "Warning: caption is ${#TEXT} characters, Telegram's limit is 1024 - the API will likely reject this message." >&2
fi

[[ "$RETRIES" =~ ^[0-9]+$ ]] && [ "$RETRIES" -ge 1 ] || RETRIES=1
# RETRY_DELAY may come from a config file - guard against non-numeric values.
[[ "$RETRY_DELAY" =~ ^[0-9]+$ ]] || RETRY_DELAY=2

# Classify one send attempt.
#   Args:  <curl_exit_status> <response_body>
#   Sets:  SEND_ERROR    - empty on success, else a human-readable reason
#          SEND_RETRYABLE - "true" only for transient failures worth retrying
#          RETRY_AFTER   - seconds requested by Telegram on 429 (0 otherwise)
evaluate_response() {
	local status="$1" response="$2" ok code desc
	SEND_ERROR=""; SEND_RETRYABLE=false; RETRY_AFTER=0

	# curl itself failed (network / proxy / timeout) -> always transient.
	if [ "$status" -ne 0 ]; then
		SEND_ERROR="curl error (exit $status)"
		SEND_RETRYABLE=true
		return
	fi

	if [ "$HAS_JQ" = true ]; then
		ok=$(jq -r '.ok' <<< "$response" 2>/dev/null)
		code=$(jq -r '.error_code // empty' <<< "$response" 2>/dev/null)
		desc=$(jq -r '.description // empty' <<< "$response" 2>/dev/null)
		RETRY_AFTER=$(jq -r '.parameters.retry_after // 0' <<< "$response" 2>/dev/null)
	else
		[[ "$response" == '{"ok":true'* ]] && ok=true || ok=false
		code=$(sed -n 's/.*"error_code":[[:space:]]*\([0-9]\{1,\}\).*/\1/p' <<< "$response")
		RETRY_AFTER=$(sed -n 's/.*"retry_after":[[:space:]]*\([0-9]\{1,\}\).*/\1/p' <<< "$response")
		desc="$response"
	fi
	[[ "$RETRY_AFTER" =~ ^[0-9]+$ ]] || RETRY_AFTER=0

	[ "$ok" = true ] && return   # success

	SEND_ERROR="Telegram error${code:+ $code}${desc:+: $desc}"
	# Retry only transient API failures: 429 (rate limit) and 5xx (server side).
	# Other errors (400/401/403/404 ...) are permanent -> fail fast, no retry.
	# If the code can't be determined, be safe and treat it as retryable.
	if [ "$code" = 429 ] || [[ "$code" =~ ^5[0-9][0-9]$ ]] || [ -z "$code" ]; then
		SEND_RETRYABLE=true
	fi
}

# Deliver the message to a single recipient, with retries.
#   Arg:    <chat_id>
#   Return: 0 if delivered, non-zero otherwise. Progress goes to stderr.
send_to_chat() {
	local id="$1" response status attempt=0 delay args
	# shellcheck disable=SC2206 # CURL_OPTIONS is a user knob; word splitting is documented
	args=($CURL_OPTIONS)
	args+=("${CURL_ARGS[@]}" --form-string "chat_id=$id" "$URL$TOKEN/$METHOD")
	while [ "$attempt" -lt "$RETRIES" ]; do
		attempt=$((attempt + 1))

		if [ "$DRY_RUN" = true ]; then
			echo "Executing: curl$(printf ' %q' "${args[@]}")"
			echo "     Text: $TEXT"
			echo
			return 0
		fi

		response=$(curl "${args[@]}" <<< "$TEXT")
		status=$?
		log "Response was: $response"
		evaluate_response "$status" "$response"

		[ -z "$SEND_ERROR" ] && return 0

		if [ "$SEND_RETRYABLE" != true ]; then
			echo "Chat $id: $SEND_ERROR - permanent, not retrying." >&2
			return 1
		fi

		echo "Chat $id: attempt $attempt of $RETRIES failed. $SEND_ERROR" >&2
		if [ "$attempt" -lt "$RETRIES" ]; then
			delay="$RETRY_DELAY"
			[ "$RETRY_AFTER" -gt "$delay" ] && delay="$RETRY_AFTER"
			sleep "$delay"
		fi
	done
	echo "Chat $id: giving up after $attempt attempt(s)." >&2
	return 1
}

FAILED_CHATS=()
if [ "$PARALLEL" = true ] && [ "$DRY_RUN" != true ]; then
	# Deliver to every recipient concurrently; collect per-chat exit codes.
	results=$(mktemp -d)
	trap 'rm -rf "$results"' EXIT
	for id in "${CHATS[@]}"; do
		( send_to_chat "$id"; echo "$?" > "$results/$id" ) &
	done
	wait
	for id in "${CHATS[@]}"; do
		[ "$(cat "$results/$id" 2>/dev/null)" = 0 ] || FAILED_CHATS+=("$id")
	done
	rm -rf "$results"
else
	for id in "${CHATS[@]}"; do
		send_to_chat "$id" || FAILED_CHATS+=("$id")
	done
fi

if [ ${#FAILED_CHATS[@]} -gt 0 ]; then
	echo "Failed to deliver to: ${FAILED_CHATS[*]}" >&2
	exit 1
fi
